name: flutter_map_heatmap
description: A heatmap plugin for flutter_map
repository: https://github.com/tprebs/fluttermap_heatmap
version: 0.0.3

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^2.0.2